name: Bug report
description: Report a bug or incorrect behavior in iSpeakerReact.
labels: ["bug"]
body:
    - type: checkboxes
      attributes:
          label: Duplicated issue check
          description: Please make sure that this issue has not been reported before.
          options:
              - label: I confirm that I have searched the existing issue(s)
                required: true
    - type: input
      id: version
      attributes:
          label: iSpeakerReact version
          description: The version of iSpeakerReact you are using. It is found in the main page of the app, window title bar, or in the App
      validations:
          required: true
    - type: textarea
      id: description
      attributes:
          label: Description
          description: Describe the bug.
      validations:
          required: true
    - type: textarea
      id: expected
      attributes:
          label: Expected behavior
          description: A concise description of what you expected to happen.
      validations:
          required: true
    - type: textarea
      id: reproduction
      attributes:
          label: Reproduction steps
          description: Steps to reproduce the behavior.
          placeholder: |
              1. Open this...
              1. Do this...
              1. See error...
      validations:
          required: true
    - type: checkboxes
      attributes:
          label: Does the app show the "App crashed" dialog?
          description: Select the checkbox if it shows, otherwise ignore this field. If you tick it, please copy the log it shows and paste it in the "Additional info" field.
          options:
              - label: The app shows the "App crashed" dialog
                required: false
    - type: dropdown
      id: os
      attributes:
          label: Operating system
          description: Which operating system are you using?
          options:
              - Windows
              - Linux
              - macOS
              - Android
              - iOS
              - Other (specify in "Additional info")
      validations:
          required: true
    - type: dropdown
      id: browser
      attributes:
          label: Browser
          description: Which browser are you using?
          options:
              - Chromium (Google Chrome, Microsoft Edge, Brave, Opera, etc.)
              - Gecko (Firefox, Librewolf, Waterfox, etc.)
              - WebKit (Safari on macOS, every browser on iOS)
              - Other (please specify in additional info)
      validations:
          required: true
    - type: textarea
      attributes:
          label: Additional info
          description: Any extra info, logs, or stack traces go here.
          placeholder: |
              Paste any error logs or useful notes here...
      validations:
          required: false
