blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/yllst-testing-labs/ispeakerreact/discussions
    about: Please ask and answer questions, or open a discussion here.
