name: Update Release Description

on:
    release:
        types: [published]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    update-release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@main

            - name: Set up Python
              uses: actions/setup-python@main
              with:
                  python-version: "3.13"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install requests

            - name: Generate release markdown
              run: |
                  python scripts/gh_releases_body.py > release_body.md

            - name: Update release (from trigger)
              if: github.event_name == 'release'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  RELEASE_ID: ${{ github.event.release.id }}
              run: |
                  BODY=$(cat release_body.md | jq -R -s '.')
                  curl -X PATCH \
                    -H "Authorization: Bearer $GITHUB_TOKEN" \
                    -H "Accept: application/vnd.github.v3+json" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID" \
                    -d "{\"body\":$BODY}"

            - name: Update release (manual or latest)
              if: github.event_name != 'release'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  BODY=$(cat release_body.md | jq -R -s '.')
                  curl -X PATCH \
                    -H "Authorization: Bearer $GITHUB_TOKEN" \
                    -H "Accept: application/vnd.github.v3+json" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    "https://api.github.com/repos/${{ github.repository }}/releases/latest" \
                    -d "{\"body\":$BODY}"
